imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3

            dependencies:
                before:
                    - composer install --no-interaction --prefer-dist --optimize-autoloader

            environment:
                APP_ENV: test

            tests:
                override:
                    - composer phpunit
                      coverage:
                          file: "docs/coverage.clover"
                          format: "php-clover"
