imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                variables:
                    APP_ENV: test

            dependencies:
                before:
                    - composer install --no-interaction --prefer-dist --optimize-autoloader

            tests:
                override:
                    -   command: "composer phpunit"
                        # command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                        coverage:
                            file: "docs/coverage.clover"
                            format: "php-clover"
