imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

        my-tests:
            environment:
                php:
                    version: 8.3.3
                node:
                    version: 16
                variables:
                    APP_ENV: test

            dependencies:
                before:
                    - composer install --no-interaction --prefer-dist --optimize-autoloader
                    - npm install
                    - npm run build

            tests:
                override:
                -   command: "composer phpunit"
                    # command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                    coverage:
                        file: "docs/coverage.clover"
                        format: "php-clover"
