imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                node:
                    version: 16
                variables:
                    APP_ENV: test

            dependencies:
                before:
                    - composer install --no-interaction --prefer-dist --optimize-autoloader
                    - npm install
                    - npm run build

            analysis:
                tests:
                    override:
                        - php-scrutinizer-run
                        
            tests:
                override:
                    - command: "XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=docs/coverage.clover"
